#!/usr/bin/env bash

dialogText=`osascript -e 'set dialogText to button returned of (display dialog "Installation complete. Start RetroArcher?" buttons {"Start", "Close"})'`;
if [[ $dialogText == 'Start' ]]
then
    open /Applications/RetroArcher.app
else
    exit 0;
fi
