#!/usr/bin/env bash

function check_retroarcher_running () {
    if pgrep -x "RetroArcher" > /dev/null
    then
        dialogText=`osascript -e 'set dialogText to button returned of (display dialog "RetroArcher is still running. Please shutdown RetroArcher before continuing." buttons {"Retry", "Abort"})'`;

        if [[ $dialogText == 'Retry' ]]
        then
            check_retroarcher_running;
        elif [[ $dialogText == 'Abort' ]]
        then
            exit 1;
        fi
    else
        exit 0;
    fi
}

check_retroarcher_running;
