name: retroarcher
adopt-info: retroarcher
summary: Retro gaming in Plex!
description: >
  RetroArcher is a gaming plug-in for Plex Media Server! The goal of RetroArcher is to use Plex as a gaming front end interface and then
  use proven game streaming technology to stream your gameplay to any of your standard Plex clients. Simply put RetroArcher is to video
  games, what Plex is to multimedia.

base: core18
confinement: strict

parts:
  retroarcher:
    plugin: dump
    source: .
    stage-packages:
      - python3.8
      - python3-openssl
      - python3-pycryptodome
      - python3-setuptools
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      TAG_FULL=$(git describe --tag)
      TAG=$(echo $TAG_FULL | grep -oP '(v\d+\.\d+\.\d+(?>-beta)?)')
      BRANCH=$(git rev-parse --abbrev-ref HEAD)
      COMMIT=$(git rev-parse HEAD)
      if [ "$TAG" = "$TAG_FULL" ]; then
        VERSION=$TAG
      else
        VERSION=$(echo $COMMIT | head -c 7)
      fi
      if [ ! "$VERSION" = "$TAG" ] || [ ! "$VERSION" = "${VERSION%-beta}" ]; then
        GRADE=devel
      else
        GRADE=stable
      fi
      if [ "$VERSION" = "$TAG" ] && [ ! "$VERSION" = "${VERSION%-beta}" ]; then
        BRANCH=beta
      elif [ "$VERSION" = "$TAG" ]; then
        BRANCH=master
      fi
      echo $BRANCH > branch.txt
      echo $COMMIT > version.txt
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"

apps:
  retroarcher:
    command: >
      usr/bin/python3 $SNAP/RetroArcher.py
        --datadir $SNAP_USER_COMMON/RetroArcher
        --config $SNAP_USER_COMMON/RetroArcher/config.ini
        --quiet
        --nolaunch
    daemon: simple
    restart-condition: on-abnormal
    restart-delay: 5s
    plugs:
      - home
      - network
      - network-bind
    environment:
      RETROARCHER_SNAP: "True"
