name: release_announcement

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f action_bots/requirements.txt ]; then pip install -r action_bots/requirements.txt; fi

      - name: reddit
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_SUBREDDIT: ${{ secrets.REDDIT_SUBREDDIT }}
        run:
          python action_bots/reddit.py

      - name: discord
          env:
            DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
            DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          run:
            python action_bots/discord_rel.py

      - name: twitter
          env:
            TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
            TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          run:
            python action_bots/twitter.py

      - name: facebook
          env:
            FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
            FACEBOOK_GROUP_ID: ${{ secrets.FACEBOOK_GROUP_ID }}
            FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          run:
            python action_bots/facebook_rel.py
